config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    get 'bank/wallet'
    get 'purchase/call'
    get 'purchase/expense'
    get 'user/information'
    get 'user/profile_image'
    get 'chat/call'
    get 'chat/friend'
    post 'purchase/verify_product'
    post 'purchase/verify_subscription'
  end

  devise_for :staffs
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :conversations, only: [:index, :show, :new, :create] do
    collection do
      get :inbox
      get :sentbox
    end
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :read_conversations, only: [:update]

  resources :matchings, only: [:index, :new, :create, :show, :destroy]

  resources :friends, only: [:index, :show]
  resource :profile, only: [:show] do
    get 'friend/:id' => 'profiles#friend'
  end
  resource :record

  resources :user_details do
    collection do
      post :image_upload
    end
  end

  resources :phone_numbers, only: [:new, :create]
  resources :verify_phone_numbers, only: [:index, :create]

  resources :paygates
  resources :badass_reports, only: [:create]
  get 'payment/payform'
  post 'payment/gateway'
  get 'purchase/verify' # in app purchase routing

  get 'users/:user_key/mobile' => 'paygates#mobile'

  authenticated :user do
    root 'matchings#index'
  end

  get 'app/index'
  root 'app#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  helper_method :mailbox, :conversation
  layout 'app', only: [:show]

  def index
  end

  def new
    @recipients = User.find(params[:recipients])
    msg = MessageService.new(current_user)
    if msg.sendings.include?(@recipients)
      chat = msg.find_chat(@recipients)
      redirect_to conversation_path(chat)
    end
  end

  def show
    conversation.receipts_for(current_user).each do |unread_receipt|
      unless unread_receipt.is_read
        unread_receipt.update(is_read: true) # 메세지 읽음으로 표시
      end
    end
    ActionCable.server.broadcast("read_conversations_#{conversation.id}", user_id: current_user.id)
  end

  def inbox
  end

  def sentbox
  end

  def create
    msg = MessageService.new(current_user)
    recipients = User.find(conversation_params(:recipients))

    unless current_user.admin_verification
      redirect_to :back, notice: '관리자의 프로필 승인대기가 이루어져야 메세지를 보내실 수 있습니다.' and return
    end

    if msg.sendings.include?(recipients)
      redirect_to conversations_path, notice: '이미 대화중인 상대방 입니다' and return
    end

    cp = 5
    if current_user.purchase(cp)
        conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation
        redirect_to api_purchase_expense_path(target_url: api_chat_call_path(conversation_id: conversation.id))
    else
      redirect_to api_purchase_call_path
    end
  end

  def reply
    receiver = (conversation.recipients - [current_user]).first
    if conversation.is_completely_trashed?(receiver)
      # redirect_to conversation_path(conversation), notice: '차단되셨습니다' and return
    else
      contents = {}
      # receipt_code 는 해당 메세지 읽었는지 확인하는 용도. receipt_id 와는 다르다.
      contents[:receipt_code] = SecureRandom.urlsafe_base64(4)
      contents[:body] = params[:message][:body]
      contents[:user_id] = current_user.id
      contents[:user_nickname] = current_user.user_detail.nickname
      contents[:user_profile] = current_user.user_detail.pic1.url(:thumb)
      ActionCable.server.broadcast("conversations_#{params[:id]}", contents)
      receipt = current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    end
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to conversation_path(conversation), notice: '차단했습니다.'
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to conversation_path(conversation), notice: '차단 해제했습니다.'
  end

  private

    def mailbox
      @mailbox ||= current_user.mailbox
    end

    def conversation
      @conversation ||= mailbox.conversations.find(params[:id])
    end

    def conversation_params(*keys)
      fetch_params(:conversation, *keys)
    end

    def message_params(*keys)
      fetch_params(:message, *keys)
    end

    def fetch_params(key, *subkeys)
      params[key].instance_eval do
        case subkeys.size
          when 0 then
            self
          when 1 then
            self[subkeys.first]
          else
            subkeys.map { |k| self[k] }
        end
      end
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:div, conversation, class: 'chal-conversations-unit') do |conversation| %>
    <%= link_to api_chat_call_path(conversation_id: conversation.id), data: { turbolinks: false } do %>
        <% unread = conversation.receipts_for(current_user).where(is_read: false).count %>
        <% sender = conversation.participants.first == current_user ? conversation.participants.last : conversation.participants.first %>
        <div class="chal-conversations-unit d-flex flex-row justify-content-between align-items-start">
          <div class="chal-conversations-profile d-flex">
            <%= image_tag "#{sender.user_detail.pic1.url(:thumb)}" %>
          </div>
          <div class="chal-conversations-main">
            <span><%= sender.user_detail.nickname %></span>
            <span><%= conversation.last_message.body %></span>
          </div>
          <div class="chal-conversations-info">
            <span class="chal-conversations-info-time"><%= time_ago_in_words(conversation.last_message.created_at) %> 전</span>
            <div class="chal-conversations-info-alarm">
              <% if conversation.is_completely_trashed?(current_user) %>
                  <span>차단함</span>
              <% elsif BadassReport.where(conversation_id: conversation).exists? %>
                  <span>신고함</span>
              <% else %>
                  <%= unread > 0 ? "<span>#{unread}</span>".html_safe : '' %>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, data: { turbolinks: false } do |f| %>
    <input type="hidden" name="conversation[recipients]" value="<%= recipients.id %>">
    <div class="form-group row" style="display: none;">
      <div class="col">
        <%= f.text_field :subject, class: 'form-control', value: current_user.id %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col">
        <p id="chal-conversation-textarea-counter">140</p>
        <%= f.text_area :body, class: 'form-control chal-conversation-body', id: 'chal-conversation-textarea', placeholder: "#{recipients.user_detail.nickname} 님에게 마음을 표현해 보세요" %>
      </div>
    </div>
    <div class="chal-sticky-submit-container">
      <%= f.submit '대화 신청', class: 'btn btn-login chal-sticky-submit-button', :data => {:confirm => '메시지 전송 및 채팅방 개설을 위해서 망고 5개가 필요 합니다.'} %>
    </div>
<% end %>

<script type="text/javascript">
  $('#chal-conversation-textarea').keyup(function () {
    maxLength = 140;
    var left = maxLength - $(this).val().length;
    if (left < 0) {
      $('#chal-conversation-textarea-counter').css("color", "red");
      $('.chal-sticky-submit-button').prop('disabled', true);
    } else {
      $('#chal-conversation-textarea-counter').css("color", "black");
      $('.chal-sticky-submit-button').prop('disabled', false);
    }
    if (70 < left) {
      $('#chal-conversation-textarea').css("font-size", "22px");
    } else {
      $('#chal-conversation-textarea').css("font-size", "20px");
    }
    $('#chal-conversation-textarea-counter').text(left);
  });
</script>

app/views/conversations/_messages_form.html.erb
<div class="chal-sticky-submit-container">
  <%= form_for :message, url: reply_conversation_path(conversation), :html => { :id => "messages-form" }, remote: true do |f| %>
      <div class="row chal-messages-row">
        <div class="col-1">
          <span id="chal-messages-textarea-counter">140</span>
        </div>
        <div class="col-11">
          <%= f.text_field :body, class: 'form-control chal-messages-body', id: 'chal-messages-textarea', placeholder: "메세지 보내기", autocomplete: 'off' %>
          <%= f.submit '전송', class: 'btn btn-login chal-messages-submit-button', id: 'messages-submit'%>
        </div>
      </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#chal-messages").scrollTop($("#chal-messages")[0].scrollHeight);
    $("#messages-form").bind("ajax:send", function(event,xhr,status){
      $('#chal-messages-textarea').val('');
      $('#chal-messages-textarea').focus();
    });
  });
</script>

app/views/conversations/inbox.html.erb
<%= render collection: mailbox.inbox, partial: 'conversation' %>

app/views/conversations/index.html.erb
<div class="chal-body">
  <% unless mailbox.conversations.present? %>
      <div class="d-flex flex-column justify-content-center chal-qna-q">
        <span class="chal-profile-header">- 인연을 찾아 대화를 시작해보세요 ! -</span>
      </div>
      <div class="d-flex flex-row align-items-center chal-qna-a">
        <span>'인연찾기' 에서 만난 인연들 중 '나의인연' 탭에 있는 상대방의 프로필 페이지에서 메시지를 보낼 수 있어요 !<br>대화가 시작된 후에는 1:1 채팅방이 열리고, 상대방과 실시간 채팅을 하실 수 있습니다.</span>
      </div>
  <% end %>
  <div class="chal-conversations">
    <%= render collection: mailbox.conversations, partial: 'conversation' %>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="chal-body">
  <a href="#" class="btn btn-outline-chal" data-toggle="modal" data-target=".modal-recipients">프로필 다시 보기</a>
  <%= render 'form', recipients: @recipients %>

  <div class="modal modal-recipients chal-modal chal-conversations-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <%= render 'components/user_profile', user: @recipients %>
        </div>
        <div class="modal-footer d-flex justify-content-end">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/sentbox.html.erb
<%= render collection: mailbox.sentbox, partial: 'conversation' %>

app/views/conversations/show.html.erb
<div class="container">
  <div class="chal-messages" id="chal-messages">
    <% @aheader = nil %>
    <%= content_tag_for(:div, conversation.receipts_for(current_user).order(id: :asc), class: 'chal-messages-unit') do |receipt| %>
        <% message = receipt.message %>
        <% sender = message.sender %>
        <% if sender == current_user %>
            <div class="chal-outgoing-messages-unit">
              <% unless @aheader == sender %>
                  <div class="d-flex chal-messages-unit-profile">
                    <p><%= current_user.user_detail.nickname %></p>
                    <%= image_tag "#{current_user.user_detail.pic1.url(:thumb)}" %>
                  </div>
              <% end %>
              <div class="chal-messages-unit-message">
                <div class="chal-messages-unit-info">
                  <span class="message-unread"><%= conversation.receipts_for(message.recipients.first).find_by_notification_id(receipt.notification_id).is_unread? ? '1' : '' %></span>
                  <span><%= time_ago_in_words(message.created_at) %>전</span>
                </div>
                <p class="chal-messages-unit-body"><%= message.body %></p>
              </div>
            </div>
        <% else %>
            <div class="chal-incoming-messages-unit">
              <% unless @aheader == sender %>
                  <div class="d-flex chal-messages-unit-profile">
                    <a href="/friends/<%= sender.id %>">
                      <%= image_tag "#{sender.user_detail.pic1.url(:thumb)}" %>
                    </a>
                    <p><%= sender.user_detail.nickname %></p>
                  </div>
              <% end %>
              <div class="chal-messages-unit-message-incoming">
                <p class="chal-messages-unit-body"><%= message.body %></p>
                <div class="chal-messages-unit-info">
                  <span><%= time_ago_in_words(message.created_at) %>전</span>
                </div>
              </div>
            </div>
        <% end %>
        <% @aheader = message.sender if @aheader != message.sender %>
    <% end %>
    <p id="chal-messages-textarea-sample"></p>
  </div>
</div>

<%= render 'messages_form', conversation: conversation %>

<div class="chal-page-options chal-page-options-top-left">
  <div class="btn-group">
    <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <div class="d-flex chal-messages-option-profile">
        <%= image_tag "#{(conversation.recipients - [current_user]).first.user_detail.pic1.url(:thumb)}" %>
      </div>
    </a>
    <div class="dropdown-menu" style="border: none;">
      <%= link_to api_chat_friend_path(id: (conversation.recipients - [current_user]).first.id), data: {turbolinks: false} do %>
          <span>프로필</span>
      <% end %>
      <% if conversation.is_completely_trashed?(current_user) %>
          <%= link_to untrash_conversation_path(conversation_id: conversation.id), method: :post, data: {confirm: '허용시 상대방이 메세지를 다시 보낼 수 있습니다.'} do %>
              <span>허용<br>하기</span>
          <% end %>
      <% else %>
          <%= link_to trash_conversation_path(conversation_id: conversation.id), method: :post, data: {confirm: '차단시 상대방이 메세지를 보낼 수 없습니다.'} do %>
              <span>차단<br>하기</span>
          <% end %>
      <% end %>
      <%= link_to badass_reports_path(conversation_id: conversation.id), method: :post do %>
          <span>신고<br>하기</span>
      <% end %>
    </div>
  </div>
</div>

<%= form_for :read_conversations, url: read_conversation_path(conversation), :html => { :id => "read-conversations-form" }, method: :put, remote: true do |f| %>
  <%= f.hidden_field :receipt_code, id: 'other-user-receipt-code' %>
<% end %>
<div id="current-user-template" data-user-id="<%= current_user.id %>" data-conversation-id="<%= conversation.id %>">
  <div data-receipt-code="0" class="mailboxer_receipt chal-messages-unit">
    <div class="chal-outgoing-messages-unit">
      <div class="chal-messages-unit-message">
        <div class="chal-messages-unit-info">
          <span class="message-unread">1</span>
          <span>1분 미만전</span>
        </div>
        <p class="chal-messages-unit-body">1</p>
      </div>
    </div>
  </div>
</div>

<div id="other-user-template">
  <div class="mailboxer_receipt chal-messages-unit">
    <div class="chal-incoming-messages-unit">
      <div class="chal-messages-unit-message-incoming">
        <p class="chal-messages-unit-body"></p>
        <div class="chal-messages-unit-info">
          <span>1분 미만전</span>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :action_js do %>
    <%= javascript_include_tag 'cable' %>
<% end %>